on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          tags: cs50/codespace:${{ github.sha }},cs50/codespace:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/codespace:${{ github.sha }}
          docker push cs50/codespace:latest

      - name: Log into GitHub Packages
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push (latest) to GitHub Packages and Microsoft Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker tag cs50/codespace:${{ github.sha }} ghcr.io/cs50/codespace:${{ github.sha }} 
          docker tag cs50/codespace:latest ghcr.io/cs50/codespace:latest
          docker tag cs50/codespace:${{ github.sha }} mcr.microsoft.com/cs50/codespace:${{ github.sha }}
          docker tag cs50/codespace:latest mcr.microsoft.com/cs50/codespace:latest
          docker push ghcr.io/cs50/codespace:${{ github.sha }}
          docker push ghcr.io/cs50/codespace:latest
          docker push mcr.microsoft.com/cs50/codespace:${{ github.sha }}
          docker push mcr.microsoft.com/cs50/codespace:latest

      - name: Tag main as latest
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/latest",
                sha: context.sha,
                force: true
              })
            } catch (e) {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/latest",
                sha: context.sha
              })
            }

      - name: Push (develop) to GitHub Packages and Microsoft Container Registry
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker tag cs50/codespace:${{ github.sha }} ghcr.io/cs50/codespace:develop
          docker tag cs50/codespace:${{ github.sha }} mcr.microsoft.com/cs50/codespace:develop
          docker push ghcr.io/cs50/codespace:develop
          docker push mcr.microsoft.com/cs50/codespace:develop